"""add theme preference column

Revision ID: abaa25333f94
Revises: f2164bef4d7c
Create Date: 2026-07-05 10:47:28.449525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abaa25333f94'
down_revision: Union[str, None] = 'f2164bef4d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('theme', sa.String(length=8), nullable=False, server_default='system'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
