"""add user preferences columns

Revision ID: b20ba274bc2b
Revises: 489d9dcb63b6
Create Date: 2026-07-05 04:31:14.689914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20ba274bc2b'
down_revision: Union[str, None] = '489d9dcb63b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('time_format', sa.String(length=8), nullable=False, server_default='24h'),
    )
    op.add_column(
        'users',
        sa.Column('accent_color', sa.String(length=16), nullable=False, server_default='#D4A72C'),
    )
    op.add_column(
        'users',
        sa.Column('compact_mode', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'users',
        sa.Column('animations_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'animations_enabled')
    op.drop_column('users', 'compact_mode')
    op.drop_column('users', 'accent_color')
    op.drop_column('users', 'time_format')
    # ### end Alembic commands ###
